#!/bin/bash
set -e

cd /usr/share/applications
sudo rm -f cmake-gui.desktop
sudo rm -f org.kde.cuttlefish.desktop
sudo rm -f xdvi.desktop
sudo rm -f mpv.desktop
sudo rm -f electron24.desktop
sudo rm -f electron26.desktop
sudo rm -f electron27.desktop
sudo rm -f electron28.desktop
sudo rm -f electron29.desktop
sudo rm -f electron30.desktop
sudo rm -f electron31.desktop
sudo rm -f electron32.desktop
sudo rm -f electron33.desktop
sudo rm -f fluid.desktop
sudo rm -f yad-icon-browser.desktop
sudo rm -f qvidcap.desktop
sudo rm -f yad-settings.desktop
sudo rm -f org.kde.kmenuedit.desktop
sudo rm -f uxterm.desktop
sudo rm -f xterm.desktop
sudo rm -f org.kde.plasmaengineexplorer.desktop
sudo rm -f org.kde.plasma.lookandfeelexplorer.desktop
sudo rm -f org.kde.plasma.themeexplorer.desktop
sudo rm -f assistant.desktop
sudo rm -f designer.desktop
sudo rm -f linguist.desktop
sudo rm -f qdbusviewer.desktop
sudo rm -f org.kde.kuserfeedback-console.desktop
sudo rm -f bssh.desktop
sudo rm -f bvnc.desktop
sudo rm -f qv4l2.desktop
sudo rm -f avahi-discover.desktop
sudo rm -f lstopo.desktop
sudo rm -f org.kde.plasma.emojier.desktop
sudo rm -f stoken-gui-small.desktop
sudo rm -f stoken-gui.desktop
sudo rm -f assistant-qt4.desktop
sudo rm -f designer-qt4.desktop
sudo rm -f linguist-qt4.desktop
sudo rm -f qdbusviewer-qt4.desktop
sudo rm -f jshell-java-openjdk.desktop
sudo rm -f jconsole-java-openjdk.desktop
sudo rm -f org.kde.discover.desktop
sudo rm -f org.kde.drkonqi.coredump.gui
sudo rm -f jconsole-java-openjdk.desktop
sudo rm -f jshell-java-openjdk.desktop
sudo rm -f vim.desktop
sudo rm -f blackmagicraw-player.desktopblackmagicraw-player.desktop
sudo rm -f blackmagicraw-player.desktop
sudo rm -f blackmagicraw-speedtest.desktop
sudo rm -f DaVinciControlPanelsSetup.desktop
sudo rm -f DaVinciResolveCaptureLogs.desktop
sudo rm -f DaVinciResolveInstaller.desktop
